### ISSUE TITLE
添加备案字段

### ISSUE THREAD

**Issue by MrQ2Geek** [adozhao/halo-theme-fresh#1]
求添加备案相关字段

**Comment by adozhao** [comment]
> 求添加备案相关字段

ok, 有时间安排上，在欢迎页开放自定义页脚（代码注入），想要添加备案号等信息稍后可自行添加

**Comment by adozhao** [comment]
@MrQ2Geek 功能已开发完成。您可在“设置-代码注入-页脚“新增如下代码添加备案信息：    

`<a href="https://baidu.com" target="_blank" style="font-size: 0.8rem;">苏ICP备11001122号</a>`    

![Snipaste_2024-06-24_11-10-38](https://github.com/adozhao/halo-theme-fresh/assets/23180747/545ee5f1-853d-4941-b6eb-3282d5b3a9a5)
